default: &default
  adapter: mysql2
  username: kiyok
  password: kiyok
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: kiyok_development

test:
  <<: *default
  database: kiyok_test

production:
  <<: *default
  database: kiyok_production
